Tiposabstractosdedatos: include/Hash.h File Reference
include/Hash.h File Reference
#include <string>
Functions
unsigned int hash (unsigned int clave)
unsigned int hash (int clave)
unsigned int hash (char clave)
unsigned int hash (std::string clave)
template<class C >
unsigned int hash (const C &clave)
Detailed Description
Declaración e implementación de funciones de localización para tipos básicos y función genérica que confía en la existencia del método método hash de las clases.
Estructura de Datos y Algoritmos Facultad de Informática Universidad Complutense de Madrid
(c) Antonio Sánchez Ruiz-Granados, 2012
Definition in file Hash.h.
Function Documentation
unsigned int hash (unsigned int clave) [inline]
Definition at line 27 of file Hash.h.
Referenced by Tabla< C, V >::amplia(), Tabla< C, V >::borra(), Tabla< C, V >::consulta(), Tabla< C, V >::esta(), and Tabla< C, V >::inserta().
unsigned int hash (int clave) [inline]
Definition at line 31 of file Hash.h.
unsigned int hash (char clave) [inline]
Definition at line 35 of file Hash.h.
unsigned int hash (std::string clave) [inline]
Definition at line 40 of file Hash.h.
template<class C > unsigned int hash (const C & clave)
Función hash genérica para clases que implementen un método publico hash.
Definition at line 56 of file Hash.h.