Tiposabstractosdedatos: PilaLE< T > Class Template Reference
PilaLE< T > Class Template Reference
#include <PilaLE.h>
Classes
class Nodo
Public Member Functions
PilaLE ()
~PilaLE ()
void apila (const T &elem)
void desapila ()
const T & cima () const
bool esVacia () const
int numElems () const
PilaLE (const PilaLE< T > &other)
PilaLE< T > & operator= (const PilaLE< T > &other)
bool operator== (const PilaLE< T > &rhs) const
bool operator!= (const PilaLE< T > &rhs) const
Protected Member Functions
void libera ()
void copia (const PilaLE &other)
Static Private Member Functions
static void libera (Nodo *prim)
Private Attributes
Nodo * _cima
int _numElems
Detailed Description
template<class T>
class PilaLE< T >
Implementación del TAD Pila utilizando vectores dinámicos.
Las operaciones son:
PilaVacia: -> Pila. Generadora implementada en el constructor sin parámetros.
apila: Pila, Elem -> Pila. Generadora
desapila: Pila - -> Pila. Modificadora parcial.
cima: Pila - -> Elem. Observadora parcial.
esVacia: Pila -> Bool. Observadora.
numElems: Pila -> Entero. Observadora.
Author:
Marco Antonio Gómez Martín
Definition at line 34 of file PilaLE.h.
Constructor & Destructor Documentation
template<class T> PilaLE< T >::PilaLE () [inline]
Constructor; operación PilaVacia
Definition at line 38 of file PilaLE.h.
template<class T> PilaLE< T >::~PilaLE () [inline]
Destructor; elimina la lista enlazada.
Definition at line 42 of file PilaLE.h.
References PilaLE< T >::_cima, and PilaLE< T >::libera().
template<class T> PilaLE< T >::PilaLE (const PilaLE< T > & other) [inline]
Constructor copia
Definition at line 118 of file PilaLE.h.
References PilaLE< T >::copia().
Member Function Documentation
template<class T> void PilaLE< T >::apila (const T & elem) [inline]
Apila un elemento. Operación generadora.
Parameters:
elem Elemento a apilar.
Definition at line 52 of file PilaLE.h.
References PilaLE< T >::_cima, and PilaLE< T >::_numElems.
template<class T> const T& PilaLE< T >::cima () const [inline]
Devuelve el elemento en la cima de la pila. Operación observadora parcial, que falla si la pila está vacía.
cima(Apila(elem, p) = elem error: cima(PilaVacia)
Returns:
Elemento en la cima de la pila.
Definition at line 82 of file PilaLE.h.
References PilaLE< T >::_cima, PilaLE< T >::Nodo::_elem, and PilaLE< T >::esVacia().
template<class T> void PilaLE< T >::copia (const PilaLE< T > & other) [inline, protected]
Definition at line 157 of file PilaLE.h.
References PilaLE< T >::_cima, PilaLE< T >::Nodo::_elem, PilaLE< T >::_numElems, PilaLE< T >::Nodo::_sig, and PilaLE< T >::esVacia().
Referenced by PilaLE< T >::operator=(), and PilaLE< T >::PilaLE().
template<class T> void PilaLE< T >::desapila () [inline]
Desapila un elemento. Operación modificadora parcial, que falla si la pila está vacía.
desapila(Apila(elem, p) = p error: desapila(PilaVacia)
Definition at line 64 of file PilaLE.h.
References PilaLE< T >::_cima, PilaLE< T >::_numElems, PilaLE< T >::Nodo::_sig, and PilaLE< T >::esVacia().
template<class T> bool PilaLE< T >::esVacia () const [inline]
Devuelve true si la pila no tiene ningún elemento.
esVacia(PilaVacia) = true esVacia(Apila(elem, p)) = false
Returns:
true si la pila no tiene ningún elemento.
Definition at line 96 of file PilaLE.h.
References PilaLE< T >::_cima.
Referenced by PilaLE< T >::cima(), PilaLE< T >::copia(), and PilaLE< T >::desapila().
template<class T> void PilaLE< T >::libera () [inline, protected]
Definition at line 153 of file PilaLE.h.
References PilaLE< T >::_cima.
Referenced by PilaLE< T >::operator=(), and PilaLE< T >::~PilaLE().
template<class T> static void PilaLE< T >::libera (Nodo * prim) [inline, static, private]
Elimina todos los nodos de la lista enlazada cuyo primer nodo se pasa como parámetro. Se admite que el nodo sea NULL (no habrá nada que liberar).
Definition at line 200 of file PilaLE.h.
References PilaLE< T >::Nodo::_sig.
template<class T> int PilaLE< T >::numElems () const [inline]
Devuelve el número de elementos que hay en la pila. numElems(PilaVacia) = 0 numElems(Apila(elem, p)) = 1 + numElems(p)
Returns:
Número de elementos.
Definition at line 108 of file PilaLE.h.
References PilaLE< T >::_numElems.
template<class T> bool PilaLE< T >::operator!= (const PilaLE< T > & rhs) const [inline]
Definition at line 147 of file PilaLE.h.
template<class T> PilaLE<T>& PilaLE< T >::operator= (const PilaLE< T > & other) [inline]
Operador de asignación
Definition at line 123 of file PilaLE.h.
References PilaLE< T >::copia(), and PilaLE< T >::libera().
template<class T> bool PilaLE< T >::operator== (const PilaLE< T > & rhs) const [inline]
Operador de comparación.
Definition at line 132 of file PilaLE.h.
References PilaLE< T >::_cima, PilaLE< T >::Nodo::_elem, PilaLE< T >::_numElems, and PilaLE< T >::Nodo::_sig.
Member Data Documentation
template<class T> Nodo* PilaLE< T >::_cima [private]
Puntero al primer elemento
Definition at line 209 of file PilaLE.h.
Referenced by PilaLE< T >::apila(), PilaLE< T >::cima(), PilaLE< T >::copia(), PilaLE< T >::desapila(), PilaLE< T >::esVacia(), PilaLE< T >::libera(), PilaLE< T >::operator==(), and PilaLE< T >::~PilaLE().
template<class T> int PilaLE< T >::_numElems [private]
Número de elementos
Definition at line 212 of file PilaLE.h.
Referenced by PilaLE< T >::apila(), PilaLE< T >::copia(), PilaLE< T >::desapila(), PilaLE< T >::numElems(), and PilaLE< T >::operator==().
The documentation for this class was generated from the following file:
include/PilaLE.h