Tiposabstractosdedatos: Cola< T > Class Template Reference
Cola< T > Class Template Reference
#include <Cola.h>
Classes
class Nodo
Public Member Functions
Cola ()
~Cola ()
void ponDetras (const T &elem)
void quitaPrim ()
const T & primero () const
bool esVacia () const
int numElems () const
Cola (const Cola< T > &other)
Cola< T > & operator= (const Cola< T > &other)
bool operator== (const Cola< T > &rhs) const
bool operator!= (const Cola< T > &rhs) const
Protected Member Functions
void libera ()
void copia (const Cola &other)
Static Private Member Functions
static void libera (Nodo *prim)
Private Attributes
Nodo * _prim
Nodo * _ult
int _numElems
Detailed Description
template<class T>
class Cola< T >
Implementación del TAD Cola utilizando una lista enlazada.
Las operaciones son:
ColaVacia: -> Cola. Generadora implementada en el constructor sin parámetros.
PonDetras: Cola, Elem -> Cola. Generadora
quitaPrim: Cola - -> Cola. Modificadora parcial.
primero: Cola - -> Elem. Observadora parcial.
esVacia: Cola -> Bool. Observadora.
numElems: Cola -> Entero. Observadora.
Author:
Marco Antonio Gómez Martín
Definition at line 34 of file Cola.h.
Constructor & Destructor Documentation
template<class T> Cola< T >::Cola () [inline]
Constructor; operacion ColaVacia
Definition at line 38 of file Cola.h.
template<class T> Cola< T >::~Cola () [inline]
Destructor; elimina la lista enlazada.
Definition at line 42 of file Cola.h.
References Cola< T >::_prim, Cola< T >::_ult, and Cola< T >::libera().
template<class T> Cola< T >::Cola (const Cola< T > & other) [inline]
Constructor copia
Definition at line 134 of file Cola.h.
References Cola< T >::copia().
Member Function Documentation
template<class T> void Cola< T >::copia (const Cola< T > & other) [inline, protected]
Definition at line 173 of file Cola.h.
References Cola< T >::Nodo::_elem, Cola< T >::_numElems, Cola< T >::_prim, Cola< T >::Nodo::_sig, Cola< T >::_ult, and Cola< T >::esVacia().
Referenced by Cola< T >::Cola(), and Cola< T >::operator=().
template<class T> bool Cola< T >::esVacia () const [inline]
Devuelve true si la cola no tiene ningún elemento.
esVacia(Cola) = true esVacia(PonDetras(elem, p)) = false
Returns:
true si la cola no tiene ningún elemento.
Definition at line 112 of file Cola.h.
References Cola< T >::_prim.
Referenced by Cola< T >::copia(), Arbin< T >::niveles(), Cola< T >::primero(), and Cola< T >::quitaPrim().
template<class T> void Cola< T >::libera () [inline, protected]
Definition at line 169 of file Cola.h.
References Cola< T >::_prim.
Referenced by Cola< T >::operator=(), and Cola< T >::~Cola().
template<class T> static void Cola< T >::libera (Nodo * prim) [inline, static, private]
Elimina todos los nodos de la lista enlazada cuyo primer nodo se pasa como parámetro. Se admite que el nodo sea NULL (no habrá nada que liberar).
Definition at line 217 of file Cola.h.
References Cola< T >::Nodo::_sig.
template<class T> int Cola< T >::numElems () const [inline]
Devuelve el número de elementos que hay en la cola. numElems(ColaVacia) = 0 numElems(PonDetras(elem, p)) = 1 + numElems(p)
Returns:
Número de elementos.
Definition at line 124 of file Cola.h.
References Cola< T >::_numElems.
template<class T> bool Cola< T >::operator!= (const Cola< T > & rhs) const [inline]
Definition at line 163 of file Cola.h.
template<class T> Cola<T>& Cola< T >::operator= (const Cola< T > & other) [inline]
Operador de asignación
Definition at line 139 of file Cola.h.
References Cola< T >::copia(), and Cola< T >::libera().
template<class T> bool Cola< T >::operator== (const Cola< T > & rhs) const [inline]
Operador de comparación.
Definition at line 148 of file Cola.h.
References Cola< T >::Nodo::_elem, Cola< T >::_numElems, Cola< T >::_prim, and Cola< T >::Nodo::_sig.
template<class T> void Cola< T >::ponDetras (const T & elem) [inline]
Añade un elemento en la parte trasera de la cola. Operación generadora.
Parameters:
elem Elemento a añadir.
Definition at line 53 of file Cola.h.
References Cola< T >::_numElems, Cola< T >::_prim, Cola< T >::Nodo::_sig, and Cola< T >::_ult.
Referenced by Arbin< T >::niveles().
template<class T> const T& Cola< T >::primero () const [inline]
Devuelve el primer elemento de la cola. Operación observadora parcial, que falla si la cola está vacía.
primero(PonDetras(elem, ColaVacia)) = elem primero(PonDetras(elem, xs)) = primero(xs) si !esVacia(xs) error: primero(ColaVacia)
Returns:
El primer elemento de la cola.
Definition at line 98 of file Cola.h.
References Cola< T >::Nodo::_elem, Cola< T >::_prim, and Cola< T >::esVacia().
Referenced by Arbin< T >::niveles().
template<class T> void Cola< T >::quitaPrim () [inline]
Elimina el primer elemento de la cola. Operación modificadora parcial, que falla si la cola está vacía.
quitaPrim(PonDetras(elem, ColaVacia)) = ColaVacia quitaPrim(PonDetras(elem, xs)) = PonDetras(elem, quitaPrim(xs)) si !esVacia(xs) error: quitaPrim(ColaVacia)
Definition at line 75 of file Cola.h.
References Cola< T >::_numElems, Cola< T >::_prim, Cola< T >::Nodo::_sig, Cola< T >::_ult, and Cola< T >::esVacia().
Referenced by Arbin< T >::niveles().
Member Data Documentation
template<class T> int Cola< T >::_numElems [private]
Número de elementos
Definition at line 232 of file Cola.h.
Referenced by Cola< T >::copia(), Cola< T >::numElems(), Cola< T >::operator==(), Cola< T >::ponDetras(), and Cola< T >::quitaPrim().
template<class T> Nodo* Cola< T >::_prim [private]
Puntero al primer elemento.
Definition at line 226 of file Cola.h.
Referenced by Cola< T >::copia(), Cola< T >::esVacia(), Cola< T >::libera(), Cola< T >::operator==(), Cola< T >::ponDetras(), Cola< T >::primero(), Cola< T >::quitaPrim(), and Cola< T >::~Cola().
template<class T> Nodo* Cola< T >::_ult [private]
Puntero al último elemento.
Definition at line 229 of file Cola.h.
Referenced by Cola< T >::copia(), Cola< T >::ponDetras(), Cola< T >::quitaPrim(), and Cola< T >::~Cola().
The documentation for this class was generated from the following file:
include/Cola.h