Tiposabstractosdedatos: Arbin< T > Class Template Reference
Arbin< T > Class Template Reference
#include <Arbin.h>
Classes
class Nodo
Public Member Functions
Arbin ()
Arbin (const Arbin &iz, const T &elem, const Arbin &dr)
~Arbin ()
const T & raiz () const
Arbin hijoIz () const
Arbin hijoDr () const
bool esVacio () const
Lista< T > preorden () const
Lista< T > inorden () const
Lista< T > postorden () const
Lista< T > niveles () const
unsigned int numNodos () const
unsigned int talla () const
unsigned int numHojas () const
Arbin (const Arbin< T > &other)
Arbin< T > & operator= (const Arbin< T > &other)
bool operator== (const Arbin< T > &rhs) const
bool operator!= (const Arbin< T > &rhs) const
Arbin ()
Arbin (const Arbin &iz, const T &elem, const Arbin &dr)
~Arbin ()
const T & raiz () const
Arbin hijoIz () const
Arbin hijoDr () const
bool esVacio () const
Lista< T > preorden () const
Lista< T > inorden () const
Lista< T > postorden () const
Lista< T > niveles () const
unsigned int numNodos () const
unsigned int talla () const
unsigned int numHojas () const
Arbin (const Arbin< T > &other)
Arbin< T > & operator= (const Arbin< T > &other)
bool operator== (const Arbin< T > &rhs) const
bool operator!= (const Arbin< T > &rhs) const
Static Public Member Functions
template<class T >
static Arbin< T > construyeYVacia (Arbin< T > &iz, const T &elem, Arbin< T > &dr)
Protected Member Functions
Arbin (Nodo *raiz)
void libera ()
void copia (const Arbin &other)
Arbin (Nodo *raiz)
void libera ()
void copia (const Arbin &other)
Static Protected Member Functions
static void preordenAcu (Nodo *ra, Lista< T > &acu)
static void inordenAcu (Nodo *ra, Lista< T > &acu)
static void postordenAcu (Nodo *ra, Lista< T > &acu)
static unsigned int numNodosAux (Nodo *ra)
static unsigned int tallaAux (Nodo *ra)
static unsigned int numHojasAux (Nodo *ra)
static void preordenAcu (Nodo *ra, Lista< T > &acu)
static void inordenAcu (Nodo *ra, Lista< T > &acu)
static void postordenAcu (Nodo *ra, Lista< T > &acu)
static unsigned int numNodosAux (Nodo *ra)
static unsigned int tallaAux (Nodo *ra)
static unsigned int numHojasAux (Nodo *ra)
Protected Attributes
Nodo * _ra
Static Private Member Functions
static void libera (Nodo *ra)
static bool comparaAux (Nodo *r1, Nodo *r2)
static void libera (Nodo *ra)
static Nodo * copiaAux (Nodo *ra)
static bool comparaAux (Nodo *r1, Nodo *r2)
Detailed Description
template<class T>
class Arbin< T >
Implementación dinámica del TAD Arbin utilizando nodos con un puntero al hijo izquierdo y otro al hijo derecho. La implementación permite compartición de estructura, manteniendola bajo control mediante conteo de referencias. La implementación, sin embargo, es bastante artesanal, pues para no complicar el código excesivamente no se ha hecho uso de punteros inteligentes que incrementen y decrementen automáticamente esas referencias.
Las operaciones son:
ArbolVacio: -> Arbin. Generadora implementada en el constructor sin parámetros.
Cons: Arbin, Elem, Arbin -> Arbin. Generadora implementada en un constructor con tres parámetros.
hijoIz, hijoDr: Arbin - -> Arbin. Observadoras que devuelven el hijo izquiero o derecho de un árbol.
esVacio: Arbin -> Bool. Observadora que devuelve si un árbol binario es vacío.
Author:
Marco Antonio Gómez Martín
Implementación dinámica del TAD Arbin utilizando nodos con un puntero al hijo izquierdo y otro al hijo derecho.
Las operaciones son:
ArbolVacio: -> Arbin. Generadora implementada en el constructor sin parámetros.
Cons: Arbin, Elem, Arbin -> Arbin. Generadora implementada en un constructor con tres parámetros.
hijoIz, hijoDr: Arbin - -> Arbin. Observadoras que devuelven el hijo izquiero o derecho de un árbol.
esVacio: Arbin -> Bool. Observadora que devuelve si un árbol binario es vacío.
Author:
Marco Antonio Gómez Martín
Definition at line 46 of file Arbin.h.
Constructor & Destructor Documentation
template<class T> Arbin< T >::Arbin () [inline]
Constructor; operacion ArbolVacio
Definition at line 50 of file Arbin.h.
Referenced by Arbin< T >::hijoDr(), and Arbin< T >::hijoIz().
template<class T> Arbin< T >::Arbin (const Arbin< T > & iz, const T & elem, const Arbin< T > & dr) [inline]
Constructor; operacion Cons
Definition at line 54 of file Arbin.h.
References Arbin< T >::_ra, and Arbin< T >::Nodo::addRef().
template<class T> Arbin< T >::~Arbin () [inline]
Destructor; elimina la estructura jerárquica de nodos.
Definition at line 60 of file Arbin.h.
References Arbin< T >::_ra, and Arbin< T >::libera().
template<class T> Arbin< T >::Arbin (const Arbin< T > & other) [inline]
Constructor copia
Definition at line 192 of file Arbin.h.
References Arbin< T >::copia().
template<class T> Arbin< T >::Arbin (Nodo * raiz) [inline, protected]
Constructor protegido que crea un árbol a partir de una estructura jerárquica existente. Esa estructura jerárquica SE COMPARTE, por lo que se añade la referencia. Se utiliza en hijoIz e hijoDr.
Definition at line 249 of file Arbin.h.
References Arbin< T >::_ra, and Arbin< T >::Nodo::addRef().
template<class T> Arbin< T >::Arbin () [inline]
Constructor; operacion ArbolVacio
Definition at line 44 of file ArbinConCopias.h.
template<class T> Arbin< T >::Arbin (const Arbin< T > & iz, const T & elem, const Arbin< T > & dr) [inline]
Constructor; operacion Cons
Definition at line 48 of file ArbinConCopias.h.
template<class T> Arbin< T >::~Arbin () [inline]
Destructor; elimina la estructura jerárquica de nodos.
Definition at line 65 of file ArbinConCopias.h.
References Arbin< T >::_ra, and Arbin< T >::libera().
template<class T> Arbin< T >::Arbin (const Arbin< T > & other) [inline]
Constructor copia
Definition at line 197 of file ArbinConCopias.h.
References Arbin< T >::copia().
template<class T> Arbin< T >::Arbin (Nodo * raiz) [inline, protected]
Constructor protegido que crea un árbol a partir de una estructura jerárquica de nodos previamente creada. Se utiliza en hijoIz e hijoDr.
Definition at line 243 of file ArbinConCopias.h.
Member Function Documentation
template<class T> static bool Arbin< T >::comparaAux (Nodo * r1, Nodo * r2) [inline, static, private]
Compara dos estructuras jerárquicas de nodos, dadas sus raices (que pueden ser NULL).
Definition at line 352 of file Arbin.h.
References Arbin< T >::Nodo::_dr, Arbin< T >::Nodo::_elem, and Arbin< T >::Nodo::_iz.
Referenced by Arbin< T >::comparaAux(), and Arbin< T >::operator==().
template<class T> static bool Arbin< T >::comparaAux (Nodo * r1, Nodo * r2) [inline, static, private]
Compara dos estructuras jerárquicas de nodos, dadas sus raices (que pueden ser NULL).
Definition at line 353 of file ArbinConCopias.h.
References Arbin< T >::Nodo::_dr, Arbin< T >::Nodo::_elem, Arbin< T >::Nodo::_iz, and Arbin< T >::comparaAux().
template<class T> template<class T > static Arbin<T> Arbin< T >::construyeYVacia (Arbin< T > & iz, const T & elem, Arbin< T > & dr) [inline, static]
Otra operación generadora (estática) que evita las copias vaciando los árboles que recibe.
Definition at line 57 of file ArbinConCopias.h.
References Arbin< T >::_ra.
template<class T> void Arbin< T >::copia (const Arbin< T > & other) [inline, protected]
Definition at line 250 of file ArbinConCopias.h.
References Arbin< T >::_ra, and Arbin< T >::copiaAux().
template<class T> void Arbin< T >::copia (const Arbin< T > & other) [inline, protected]
Definition at line 258 of file Arbin.h.
References Arbin< T >::_ra, and Arbin< T >::Nodo::addRef().
Referenced by Arbin< T >::Arbin(), and Arbin< T >::operator=().
template<class T> static Nodo* Arbin< T >::copiaAux (Nodo * ra) [inline, static, private]
Copia la estructura jerárquica de nodos pasada como parámetro (puntero a su raiz) y devuelve un puntero a una nueva estructura jerárquica, copia de anterior (y que, por tanto, habrá que liberar).
Definition at line 340 of file ArbinConCopias.h.
References Arbin< T >::Nodo::_dr, Arbin< T >::Nodo::_elem, and Arbin< T >::Nodo::_iz.
Referenced by Arbin< T >::copia(), Arbin< T >::hijoDr(), and Arbin< T >::hijoIz().
template<class T> bool Arbin< T >::esVacio () const [inline]
Operación observadora que devuelve si el árbol es vacío (no contiene elementos) o no.
esVacio(ArbolVacio) = true esVacio(Cons(iz, elem, dr)) = false
Definition at line 113 of file Arbin.h.
References Arbin< T >::_ra.
Referenced by Arbin< T >::hijoDr(), Arbin< T >::hijoIz(), Arbin< T >::niveles(), and Arbin< T >::raiz().
template<class T> bool Arbin< T >::esVacio () const [inline]
Operación observadora que devuelve si el árbol es vacío (no contiene elementos) o no.
esVacio(ArbolVacio) = true esVacio(Cons(iz, elem, dr)) = false
Definition at line 118 of file ArbinConCopias.h.
References Arbin< T >::_ra.
template<class T> Arbin Arbin< T >::hijoDr () const [inline]
Devuelve un árbol copia del árbol derecho. Es una operación parcial (falla con el árbol vacío).
hijoDr(Cons(iz, elem, dr)) = dr error hijoDr(ArbolVacio)
Definition at line 99 of file Arbin.h.
References Arbin< T >::Nodo::_dr, Arbin< T >::_ra, Arbin< T >::Arbin(), and Arbin< T >::esVacio().
template<class T> Arbin Arbin< T >::hijoDr () const [inline]
Devuelve un árbol copia del árbol derecho. Es una operación parcial (falla con el árbol vacío).
hijoDr(Cons(iz, elem, dr)) = dr error hijoDr(ArbolVacio)
Definition at line 104 of file ArbinConCopias.h.
References Arbin< T >::Nodo::_dr, Arbin< T >::_ra, Arbin< T >::Arbin(), Arbin< T >::copiaAux(), and Arbin< T >::esVacio().
template<class T> Arbin Arbin< T >::hijoIz () const [inline]
Devuelve un árbol copia del árbol izquierdo. Es una operación parcial (falla con el árbol vacío).
hijoIz(Cons(iz, elem, dr)) = iz error hijoIz(ArbolVacio)
Definition at line 85 of file Arbin.h.
References Arbin< T >::Nodo::_iz, Arbin< T >::_ra, Arbin< T >::Arbin(), and Arbin< T >::esVacio().
template<class T> Arbin Arbin< T >::hijoIz () const [inline]
Devuelve un árbol copia del árbol izquierdo. Es una operación parcial (falla con el árbol vacío).
hijoIz(Cons(iz, elem, dr)) = iz error hijoIz(ArbolVacio)
Definition at line 90 of file ArbinConCopias.h.
References Arbin< T >::Nodo::_iz, Arbin< T >::_ra, Arbin< T >::Arbin(), Arbin< T >::copiaAux(), and Arbin< T >::esVacio().
template<class T> Lista<T> Arbin< T >::inorden () const [inline]
Definition at line 127 of file Arbin.h.
References Arbin< T >::_ra, and Arbin< T >::inordenAcu().
template<class T> Lista<T> Arbin< T >::inorden () const [inline]
Definition at line 132 of file ArbinConCopias.h.
References Arbin< T >::_ra, and Arbin< T >::inordenAcu().
template<class T> static void Arbin< T >::inordenAcu (Nodo * ra, Lista< T > & acu) [inline, static, protected]
Definition at line 267 of file ArbinConCopias.h.
References Arbin< T >::Nodo::_dr, Arbin< T >::Nodo::_elem, Arbin< T >::Nodo::_iz, Arbin< T >::inordenAcu(), and Lista< T >::ponDr().
template<class T> static void Arbin< T >::inordenAcu (Nodo * ra, Lista< T > & acu) [inline, static, protected]
Definition at line 278 of file Arbin.h.
References Arbin< T >::Nodo::_dr, Arbin< T >::Nodo::_elem, Arbin< T >::Nodo::_iz, and Lista< T >::ponDr().
Referenced by Arbin< T >::inorden(), and Arbin< T >::inordenAcu().
template<class T> void Arbin< T >::libera () [inline, protected]
Definition at line 246 of file ArbinConCopias.h.
References Arbin< T >::_ra, and Arbin< T >::libera().
template<class T> void Arbin< T >::libera () [inline, protected]
Definition at line 254 of file Arbin.h.
References Arbin< T >::_ra.
Referenced by Arbin< T >::libera(), Arbin< T >::operator=(), and Arbin< T >::~Arbin().
template<class T> static void Arbin< T >::libera (Nodo * ra) [inline, static, private]
Elimina todos los nodos de una estructura arbórea que comienza con el puntero ra. Se admite que el nodo sea NULL (no habrá nada que liberar).
Definition at line 326 of file ArbinConCopias.h.
References Arbin< T >::Nodo::_dr, Arbin< T >::Nodo::_iz, and Arbin< T >::libera().
template<class T> static void Arbin< T >::libera (Nodo * ra) [inline, static, private]
Elimina todos los nodos de una estructura arbórea que comienza con el puntero ra. Se admite que el nodo sea NULL (no habrá nada que liberar).
Definition at line 337 of file Arbin.h.
References Arbin< T >::Nodo::_dr, Arbin< T >::Nodo::_iz, Arbin< T >::Nodo::_numRefs, Arbin< T >::libera(), and Arbin< T >::Nodo::remRef().
template<class T> Lista<T> Arbin< T >::niveles () const [inline]
Definition at line 139 of file Arbin.h.
References Arbin< T >::Nodo::_dr, Arbin< T >::Nodo::_elem, Arbin< T >::Nodo::_iz, Arbin< T >::_ra, Cola< T >::esVacia(), Arbin< T >::esVacio(), Cola< T >::ponDetras(), Lista< T >::ponDr(), Cola< T >::primero(), and Cola< T >::quitaPrim().
template<class T> Lista<T> Arbin< T >::niveles () const [inline]
Definition at line 144 of file ArbinConCopias.h.
References Arbin< T >::Nodo::_dr, Arbin< T >::Nodo::_elem, Arbin< T >::Nodo::_iz, Arbin< T >::_ra, Cola< T >::esVacia(), Arbin< T >::esVacio(), Cola< T >::ponDetras(), Lista< T >::ponDr(), Cola< T >::primero(), and Cola< T >::quitaPrim().
template<class T> unsigned int Arbin< T >::numHojas () const [inline]
Devuelve el número de hojas de un árbol.
Definition at line 182 of file Arbin.h.
References Arbin< T >::_ra, and Arbin< T >::numHojasAux().
template<class T> unsigned int Arbin< T >::numHojas () const [inline]
Devuelve el número de hojas de un árbol.
Definition at line 187 of file ArbinConCopias.h.
References Arbin< T >::_ra, and Arbin< T >::numHojasAux().
template<class T> static unsigned int Arbin< T >::numHojasAux (Nodo * ra) [inline, static, protected]
Definition at line 308 of file ArbinConCopias.h.
References Arbin< T >::Nodo::_dr, Arbin< T >::Nodo::_iz, and Arbin< T >::numHojasAux().
template<class T> static unsigned int Arbin< T >::numHojasAux (Nodo * ra) [inline, static, protected]
Definition at line 319 of file Arbin.h.
References Arbin< T >::Nodo::_dr, and Arbin< T >::Nodo::_iz.
Referenced by Arbin< T >::numHojas(), and Arbin< T >::numHojasAux().
template<class T> unsigned int Arbin< T >::numNodos () const [inline]
Devuelve el número de nodos de un árbol.
Definition at line 168 of file Arbin.h.
References Arbin< T >::_ra, and Arbin< T >::numNodosAux().
template<class T> unsigned int Arbin< T >::numNodos () const [inline]
Devuelve el número de nodos de un árbol.
Definition at line 173 of file ArbinConCopias.h.
References Arbin< T >::_ra, and Arbin< T >::numNodosAux().
template<class T> static unsigned int Arbin< T >::numNodosAux (Nodo * ra) [inline, static, protected]
Definition at line 290 of file ArbinConCopias.h.
References Arbin< T >::Nodo::_dr, Arbin< T >::Nodo::_iz, and Arbin< T >::numNodosAux().
template<class T> static unsigned int Arbin< T >::numNodosAux (Nodo * ra) [inline, static, protected]
Definition at line 301 of file Arbin.h.
References Arbin< T >::Nodo::_dr, and Arbin< T >::Nodo::_iz.
Referenced by Arbin< T >::numNodos(), and Arbin< T >::numNodosAux().
template<class T> bool Arbin< T >::operator!= (const Arbin< T > & rhs) const [inline]
Definition at line 210 of file Arbin.h.
template<class T> bool Arbin< T >::operator!= (const Arbin< T > & rhs) const [inline]
Definition at line 215 of file ArbinConCopias.h.
template<class T> Arbin<T>& Arbin< T >::operator= (const Arbin< T > & other) [inline]
Operador de asignación
Definition at line 197 of file Arbin.h.
References Arbin< T >::copia(), and Arbin< T >::libera().
template<class T> Arbin<T>& Arbin< T >::operator= (const Arbin< T > & other) [inline]
Operador de asignación
Definition at line 202 of file ArbinConCopias.h.
References Arbin< T >::copia(), and Arbin< T >::libera().
template<class T> bool Arbin< T >::operator== (const Arbin< T > & rhs) const [inline]
Operador de comparación.
Definition at line 206 of file Arbin.h.
References Arbin< T >::_ra, and Arbin< T >::comparaAux().
template<class T> bool Arbin< T >::operator== (const Arbin< T > & rhs) const [inline]
Operador de comparación.
Definition at line 211 of file ArbinConCopias.h.
References Arbin< T >::_ra, and Arbin< T >::comparaAux().
template<class T> Lista<T> Arbin< T >::postorden () const [inline]
Definition at line 133 of file Arbin.h.
References Arbin< T >::_ra, and Arbin< T >::postordenAcu().
template<class T> Lista<T> Arbin< T >::postorden () const [inline]
Definition at line 138 of file ArbinConCopias.h.
References Arbin< T >::_ra, and Arbin< T >::postordenAcu().
template<class T> static void Arbin< T >::postordenAcu (Nodo * ra, Lista< T > & acu) [inline, static, protected]
Definition at line 276 of file ArbinConCopias.h.
References Arbin< T >::Nodo::_dr, Arbin< T >::Nodo::_elem, Arbin< T >::Nodo::_iz, Lista< T >::ponDr(), and Arbin< T >::postordenAcu().
template<class T> static void Arbin< T >::postordenAcu (Nodo * ra, Lista< T > & acu) [inline, static, protected]
Definition at line 287 of file Arbin.h.
References Arbin< T >::Nodo::_dr, Arbin< T >::Nodo::_elem, Arbin< T >::Nodo::_iz, and Lista< T >::ponDr().
Referenced by Arbin< T >::postorden(), and Arbin< T >::postordenAcu().
template<class T> Lista<T> Arbin< T >::preorden () const [inline]
Definition at line 121 of file Arbin.h.
References Arbin< T >::_ra, and Arbin< T >::preordenAcu().
template<class T> Lista<T> Arbin< T >::preorden () const [inline]
Definition at line 126 of file ArbinConCopias.h.
References Arbin< T >::_ra, and Arbin< T >::preordenAcu().
template<class T> static void Arbin< T >::preordenAcu (Nodo * ra, Lista< T > & acu) [inline, static, protected]
Definition at line 258 of file ArbinConCopias.h.
References Arbin< T >::Nodo::_dr, Arbin< T >::Nodo::_elem, Arbin< T >::Nodo::_iz, Lista< T >::ponDr(), and Arbin< T >::preordenAcu().
template<class T> static void Arbin< T >::preordenAcu (Nodo * ra, Lista< T > & acu) [inline, static, protected]
Definition at line 269 of file Arbin.h.
References Arbin< T >::Nodo::_dr, Arbin< T >::Nodo::_elem, Arbin< T >::Nodo::_iz, and Lista< T >::ponDr().
Referenced by Arbin< T >::preorden(), and Arbin< T >::preordenAcu().
template<class T> const T& Arbin< T >::raiz () const [inline]
Devuelve el elemento almacenado en la raiz
raiz(Cons(iz, elem, dr)) = elem error raiz(ArbolVacio)
Returns:
Elemento en la raíz.
Definition at line 72 of file Arbin.h.
References Arbin< T >::Nodo::_elem, Arbin< T >::_ra, and Arbin< T >::esVacio().
template<class T> const T& Arbin< T >::raiz () const [inline]
Devuelve el elemento almacenado en la raiz
raiz(Cons(iz, elem, dr)) = elem error raiz(ArbolVacio)
Returns:
Elemento en la raíz.
Definition at line 77 of file ArbinConCopias.h.
References Arbin< T >::Nodo::_elem, Arbin< T >::_ra, and Arbin< T >::esVacio().
template<class T> unsigned int Arbin< T >::talla () const [inline]
Devuelve la talla del árbol.
Definition at line 175 of file Arbin.h.
References Arbin< T >::_ra, and Arbin< T >::tallaAux().
template<class T> unsigned int Arbin< T >::talla () const [inline]
Devuelve la talla del árbol.
Definition at line 180 of file ArbinConCopias.h.
References Arbin< T >::_ra, and Arbin< T >::tallaAux().
template<class T> static unsigned int Arbin< T >::tallaAux (Nodo * ra) [inline, static, protected]
Definition at line 296 of file ArbinConCopias.h.
References Arbin< T >::Nodo::_dr, Arbin< T >::Nodo::_iz, and Arbin< T >::tallaAux().
template<class T> static unsigned int Arbin< T >::tallaAux (Nodo * ra) [inline, static, protected]
Definition at line 307 of file Arbin.h.
References Arbin< T >::Nodo::_dr, and Arbin< T >::Nodo::_iz.
Referenced by Arbin< T >::talla(), and Arbin< T >::tallaAux().
Member Data Documentation
template<class T> Nodo * Arbin< T >::_ra [protected]
Puntero a la raíz de la estructura jerárquica de nodos.
Definition at line 373 of file Arbin.h.
Referenced by Arbin< T >::Arbin(), Arbin< T >::construyeYVacia(), Arbin< T >::copia(), Arbin< T >::esVacio(), Arbin< T >::hijoDr(), Arbin< T >::hijoIz(), Arbin< T >::inorden(), Arbin< T >::libera(), Arbin< T >::niveles(), Arbin< T >::numHojas(), Arbin< T >::numNodos(), Arbin< T >::operator==(), Arbin< T >::postorden(), Arbin< T >::preorden(), Arbin< T >::raiz(), Arbin< T >::talla(), and Arbin< T >::~Arbin().
The documentation for this class was generated from the following files:
include/Arbin.h
include/ArbinConCopias.h