Tiposabstractosdedatos: Fecha Class Reference
Fecha Class Reference
#include <Fecha.h>
Public Member Functions
Fecha (int dia, int mes, int anyo)
Fecha (const Fecha &base, int delta)
int distancia (const Fecha &otra) const
int dia () const
int diaSemana () const
int mes () const
int anyo () const
int diaAnyo () const
virtual ~Fecha ()
Private Attributes
int _dia
int _mes
int _anyo
Detailed Description
Definition at line 13 of file Fecha.h.
Constructor & Destructor Documentation
Fecha::Fecha (int dia, int mes, int anyo)
Definition at line 13 of file Fecha.cpp.
Fecha::Fecha (const Fecha & base, int delta)
Definition at line 19 of file Fecha.cpp.
References anyo(), dia(), and mes().
Fecha::~Fecha () [virtual]
Definition at line 52 of file Fecha.cpp.
Member Function Documentation
int Fecha::anyo () const
Definition at line 44 of file Fecha.cpp.
Referenced by Fecha().
int Fecha::dia () const
Definition at line 32 of file Fecha.cpp.
Referenced by Fecha().
int Fecha::diaAnyo () const
Definition at line 48 of file Fecha.cpp.
int Fecha::diaSemana () const
Definition at line 36 of file Fecha.cpp.
int Fecha::distancia (const Fecha & otra) const
Definition at line 25 of file Fecha.cpp.
int Fecha::mes () const
Definition at line 40 of file Fecha.cpp.
Referenced by Fecha().
Member Data Documentation
int Fecha::_anyo [private]
Definition at line 29 of file Fecha.h.
int Fecha::_dia [private]
Definition at line 27 of file Fecha.h.
int Fecha::_mes [private]
Definition at line 28 of file Fecha.h.
The documentation for this class was generated from the following files:
include/Fecha.h
src/Fecha.cpp