Tiposabstractosdedatos: Tabla< C, V > Class Template Reference
Tabla< C, V > Class Template Reference
#include <Tabla.h>
Classes
class Iterador
class Nodo
Public Member Functions
Tabla ()
~Tabla ()
void inserta (const C &clave, const V &valor)
void borra (const C &clave)
bool esta (const C &clave)
const V & consulta (const C &clave)
bool esVacia ()
Iterador principio ()
Iterador final () const
Tabla (const Tabla< C, V > &other)
Tabla< C, V > & operator= (const Tabla< C, V > &other)
Static Public Attributes
static const int TAM_INICIAL = 10
Private Member Functions
void libera ()
void copia (const Tabla< C, V > &other)
void amplia ()
Static Private Member Functions
static void liberaNodos (Nodo *prim)
static void buscaNodo (const C &clave, Nodo *&act, Nodo *&ant)
static Nodo * buscaNodo (const C &clave, Nodo *prim)
Private Attributes
Nodo ** _v
Array de punteros a Nodo.
unsigned int _tam
Tamaño del array _v.
unsigned int _numElems
Número de elementos en la tabla.
Static Private Attributes
static const unsigned int MAX_OCUPACION = 80
Friends
class Iterador
Detailed Description
template<class C, class V>
class Tabla< C, V >
Implementación del TAD Tabla usando una tabla hash abierta.
Las operaciones públicas son:
TablaVacia: -> Tabla. Generadora (constructor).
inserta: Tabla, Clave, Valor -> Tabla. Generadora.
borra: Tabla, Clave -> Tabla. Modificadora.
esta: Tabla, Clave -> Bool. Observadora.
consulta: Tabla, Clave - -> Valor. Observadora parcial.
esVacia: Tabla -> Bool. Observadora.
Author:
Antonio Sánchez Ruiz-Granados
Definition at line 48 of file Tabla.h.
Constructor & Destructor Documentation
template<class C, class V> Tabla< C, V >::Tabla () [inline]
Constructor por defecto. Crea una tabla con TAM_INICIAL posiciones.
Definition at line 81 of file Tabla.h.
References Tabla< C, V >::_tam, and Tabla< C, V >::_v.
template<class C, class V> Tabla< C, V >::~Tabla () [inline]
Destructor.
Definition at line 90 of file Tabla.h.
References Tabla< C, V >::libera().
template<class C, class V> Tabla< C, V >::Tabla (const Tabla< C, V > & other) [inline]
Constructor por copia.
Parameters:
other tabla que se quiere copiar.
Definition at line 290 of file Tabla.h.
References Tabla< C, V >::copia().
Member Function Documentation
template<class C, class V> void Tabla< C, V >::amplia () [inline, private]
Este método duplica la capacidad del array de punteros actual.
Definition at line 373 of file Tabla.h.
References Tabla< C, V >::Nodo::_clave, Tabla< C, V >::Nodo::_sig, Tabla< C, V >::_tam, Tabla< C, V >::_v, and hash().
Referenced by Tabla< C, V >::inserta().
template<class C, class V> void Tabla< C, V >::borra (const C & clave) [inline]
Elimina el elemento de la tabla con la clave dada. Si no existía ningún elemento con dicha clave, la tabla no se modifica.
Parameters:
clave clave del elemento a eliminar.
Definition at line 130 of file Tabla.h.
References Tabla< C, V >::_numElems, Tabla< C, V >::Nodo::_sig, Tabla< C, V >::_tam, Tabla< C, V >::_v, Tabla< C, V >::buscaNodo(), and hash().
template<class C, class V> static void Tabla< C, V >::buscaNodo (const C & clave, Nodo *& act, Nodo *& ant) [inline, static, private]
Busca un nodo a partir del nodo "act" que contenga la clave dada. Si lo encuentra, "act" quedará apuntando a dicho nodo y "ant" al nodo anterior. Si no lo encuentra "act" quedará apuntando a NULL.
Parameters:
clave clave del nodo que se busca.
act [in/out] inicialmente indica el primer nodo de la búsqueda y al finalizar indica el nodo encontrado o NULL.
ant [out] puntero al nodo anterior a "act" o NULL.
Definition at line 423 of file Tabla.h.
References Tabla< C, V >::Nodo::_clave, and Tabla< C, V >::Nodo::_sig.
Referenced by Tabla< C, V >::borra(), Tabla< C, V >::buscaNodo(), Tabla< C, V >::consulta(), Tabla< C, V >::esta(), and Tabla< C, V >::inserta().
template<class C, class V> static Nodo* Tabla< C, V >::buscaNodo (const C & clave, Nodo * prim) [inline, static, private]
Busca un nodo a partir de "prim" que contenga la clave dada. A diferencia del otro método "buscaNodo", este no devuelve un puntero al nodo anterior.
Parameters:
clave clave del nodo que se busca.
prim nodo a partir del cual realizar la búsqueda.
Returns:
nodo encontrado o NULL.
Definition at line 447 of file Tabla.h.
References Tabla< C, V >::buscaNodo().
template<class C, class V> const V& Tabla< C, V >::consulta (const C & clave) [inline]
Devuelve el valor asociado a la clave dada. Si la tabla no contiene esa clave lanza una excepción.
Parameters:
clave clave del elemento a buscar.
Returns:
valor asociado a dicha clave.
Exceptions:
EClaveInexistente si la clave no existe en la tabla.
Definition at line 178 of file Tabla.h.
References Tabla< C, V >::_tam, Tabla< C, V >::_v, Tabla< C, V >::Nodo::_valor, Tabla< C, V >::buscaNodo(), and hash().
template<class C, class V> void Tabla< C, V >::copia (const Tabla< C, V > & other) [inline, private]
Hace una copia de la tabla que recibe como parámetro. Antes de llamar a este método se debe invocar al método "liberar".
Parameters:
other tabla que se quiere copiar.
Definition at line 351 of file Tabla.h.
References Tabla< C, V >::Nodo::_clave, Tabla< C, V >::_numElems, Tabla< C, V >::Nodo::_sig, Tabla< C, V >::_tam, Tabla< C, V >::_v, and Tabla< C, V >::Nodo::_valor.
Referenced by Tabla< C, V >::operator=(), and Tabla< C, V >::Tabla().
template<class C, class V> bool Tabla< C, V >::esta (const C & clave) [inline]
Comprueba si la tabla contiene algún elemento con la clave dada.
Parameters:
clave clave a buscar.
Returns:
si existe algún elemento con esa clave.
Definition at line 161 of file Tabla.h.
References Tabla< C, V >::_tam, Tabla< C, V >::_v, Tabla< C, V >::buscaNodo(), and hash().
template<class C, class V> bool Tabla< C, V >::esVacia () [inline]
Indica si la tabla está vacía, es decir, si no contiene ningún elemento.
Returns:
si la tabla está vacía.
Definition at line 196 of file Tabla.h.
References Tabla< C, V >::_numElems.
template<class C, class V> Iterador Tabla< C, V >::final () const [inline]
Devuelve un iterador al final del recorrido (apunta más allá del último elemento de la tabla).
Returns:
iterador al final del recorrido.
Definition at line 276 of file Tabla.h.
References Tabla< C, V >::_tam, and Tabla< C, V >::Iterador.
template<class C, class V> void Tabla< C, V >::inserta (const C & clave, const V & valor) [inline]
Inserta un nuevo par (clave, valor) en la tabla. Si ya existía un elemento con esa clave, se actualiza su valor.
Parameters:
clave clave del nuevo elemento.
valor valor del nuevo elemento.
Definition at line 101 of file Tabla.h.
References Tabla< C, V >::_numElems, Tabla< C, V >::_tam, Tabla< C, V >::_v, Tabla< C, V >::Nodo::_valor, Tabla< C, V >::amplia(), Tabla< C, V >::buscaNodo(), hash(), and Tabla< C, V >::MAX_OCUPACION.
template<class C, class V> void Tabla< C, V >::libera () [inline, private]
Libera toda la memoria dinámica reservada para la tabla.
Definition at line 317 of file Tabla.h.
References Tabla< C, V >::_tam, Tabla< C, V >::_v, and Tabla< C, V >::liberaNodos().
Referenced by Tabla< C, V >::operator=(), and Tabla< C, V >::~Tabla().
template<class C, class V> static void Tabla< C, V >::liberaNodos (Nodo * prim) [inline, static, private]
Libera un nodo y todos los siguientes.
Parameters:
prim puntero al primer nodo de la lista a liberar.
Definition at line 336 of file Tabla.h.
References Tabla< C, V >::Nodo::_sig.
Referenced by Tabla< C, V >::libera().
template<class C, class V> Tabla<C,V>& Tabla< C, V >::operator= (const Tabla< C, V > & other) [inline]
Operador de asignación.
Parameters:
other tabla que se quiere copiar.
Returns:
referencia a este mismo objeto (*this).
Definition at line 300 of file Tabla.h.
References Tabla< C, V >::copia(), and Tabla< C, V >::libera().
template<class C, class V> Iterador Tabla< C, V >::principio () [inline]
Devuelve un iterador al primer par (clave, valor) de la tabla. El iterador devuelto coincidirá con final() si la tabla está vacía.
Returns:
iterador al primer par (clave, valor) de la tabla.
Definition at line 258 of file Tabla.h.
References Tabla< C, V >::_tam, Tabla< C, V >::_v, and Tabla< C, V >::Iterador.
Friends And Related Function Documentation
template<class C, class V> friend class Iterador [friend]
Definition at line 312 of file Tabla.h.
Referenced by Tabla< C, V >::final(), and Tabla< C, V >::principio().
Member Data Documentation
template<class C, class V> unsigned int Tabla< C, V >::_numElems [private]
Número de elementos en la tabla.
Definition at line 462 of file Tabla.h.
Referenced by Tabla< C, V >::borra(), Tabla< C, V >::copia(), Tabla< C, V >::esVacia(), and Tabla< C, V >::inserta().
template<class C, class V> unsigned int Tabla< C, V >::_tam [private]
Tamaño del array _v.
Definition at line 461 of file Tabla.h.
Referenced by Tabla< C, V >::amplia(), Tabla< C, V >::Iterador::avanza(), Tabla< C, V >::borra(), Tabla< C, V >::consulta(), Tabla< C, V >::copia(), Tabla< C, V >::esta(), Tabla< C, V >::final(), Tabla< C, V >::inserta(), Tabla< C, V >::libera(), Tabla< C, V >::principio(), and Tabla< C, V >::Tabla().
template<class C, class V> Nodo** Tabla< C, V >::_v [private]
Array de punteros a Nodo.
Definition at line 460 of file Tabla.h.
Referenced by Tabla< C, V >::amplia(), Tabla< C, V >::Iterador::avanza(), Tabla< C, V >::borra(), Tabla< C, V >::consulta(), Tabla< C, V >::copia(), Tabla< C, V >::esta(), Tabla< C, V >::inserta(), Tabla< C, V >::libera(), Tabla< C, V >::principio(), and Tabla< C, V >::Tabla().
template<class C, class V> const unsigned int Tabla< C, V >::MAX_OCUPACION = 80 [static, private]
Ocupación máxima permitida antes de ampliar la tabla en tanto por cientos.
Definition at line 457 of file Tabla.h.
Referenced by Tabla< C, V >::inserta().
template<class C, class V> const int Tabla< C, V >::TAM_INICIAL = 10 [static]
Tamaño inicial de la tabla.
Definition at line 75 of file Tabla.h.
The documentation for this class was generated from the following file:
include/Tabla.h