Tiposabstractosdedatos: Lista< T >::Iterador Class Reference
Lista< T >::Iterador Class Reference
#include <Lista.h>
Public Member Functions
void avanza ()
const T & elem () const
void pon (const T &elem)
bool operator== (const Iterador &other) const
bool operator!= (const Iterador &other) const
Protected Member Functions
Iterador ()
Iterador (Nodo *act)
Protected Attributes
Nodo * _act
Friends
class Lista
Detailed Description
template<class T>
class Lista< T >::Iterador
Clase interna que implementa un iterador sobre la lista que permite recorrer la lista e incluso alterar el valor de sus elementos.
Definition at line 225 of file Lista.h.
Constructor & Destructor Documentation
template<class T> Lista< T >::Iterador::Iterador () [inline, protected]
Definition at line 254 of file Lista.h.
template<class T> Lista< T >::Iterador::Iterador (Nodo * act) [inline, protected]
Definition at line 255 of file Lista.h.
Member Function Documentation
template<class T> void Lista< T >::Iterador::avanza () [inline]
Definition at line 227 of file Lista.h.
References Lista< T >::Iterador::_act, and Lista< T >::Nodo::_sig.
template<class T> const T& Lista< T >::Iterador::elem () const [inline]
Definition at line 232 of file Lista.h.
References Lista< T >::Iterador::_act, and Lista< T >::Nodo::_elem.
Referenced by Lista< T >::Iterador::pon().
template<class T> bool Lista< T >::Iterador::operator!= (const Iterador & other) const [inline]
Definition at line 246 of file Lista.h.
References Lista< T >::Iterador::operator==().
template<class T> bool Lista< T >::Iterador::operator== (const Iterador & other) const [inline]
Definition at line 242 of file Lista.h.
References Lista< T >::Iterador::_act.
Referenced by Lista< T >::Iterador::operator!=().
template<class T> void Lista< T >::Iterador::pon (const T & elem) [inline]
Definition at line 237 of file Lista.h.
References Lista< T >::Iterador::_act, Lista< T >::Nodo::_elem, and Lista< T >::Iterador::elem().
Friends And Related Function Documentation
template<class T> friend class Lista [friend]
Definition at line 252 of file Lista.h.
Member Data Documentation
template<class T> Nodo* Lista< T >::Iterador::_act [protected]
Definition at line 258 of file Lista.h.
Referenced by Lista< T >::Iterador::avanza(), Lista< T >::borra(), Lista< T >::Iterador::elem(), Lista< T >::insertar(), Lista< T >::Iterador::operator==(), and Lista< T >::Iterador::pon().
The documentation for this class was generated from the following file:
include/Lista.h