Tiposabstractosdedatos: DCola< T > Class Template Reference
DCola< T > Class Template Reference
#include <DCola.h>
Classes
class Nodo
Public Member Functions
DCola ()
~DCola ()
void ponDetras (const T &e)
const T & primero () const
void quitaPrim ()
void ponDelante (const T &e)
const T & ultimo () const
void quitaUlt ()
bool esVacia () const
int numElems () const
DCola (const DCola< T > &other)
DCola< T > & operator= (const DCola< T > &other)
bool operator== (const DCola< T > &rhs) const
bool operator!= (const DCola< T > &rhs) const
Protected Member Functions
void libera ()
void copia (const DCola< T > &other)
Static Private Member Functions
static Nodo * insertaElem (const T &e, Nodo *nodo1, Nodo *nodo2)
static void borraElem (Nodo *n)
static void libera (Nodo *prim)
Private Attributes
Nodo * _fantasma
unsigned int _numElems
Detailed Description
template<class T>
class DCola< T >
Implementación del TAD Doble Cola utilizando una lista doblemente enlazada circular y con nodo fantasma.
Las operaciones son:
DColaVacia: -> DCola. Generadora implementada en el constructor sin parámetros.
PonDetras: DCola, Elem -> DCola. Generadora
ponDelante: DCola, Elem -> DCola. Modificadora.
quitaPrim: DCola - -> DCola. Modificadora parcial
primero: DCola - -> Elem. Observadora parcial
quitaUlt: DCola - -> DCola. Modificadora parcial
ultimo: DCola - -> Elem. Observadora parcial
esVacia: DCola -> Bool. Observadora
Author:
Marco Antonio Gómez Martín
Definition at line 38 of file DCola.h.
Constructor & Destructor Documentation
template<class T> DCola< T >::DCola () [inline]
Constructor; operación DColaVacia.
Definition at line 42 of file DCola.h.
References DCola< T >::Nodo::_ant, DCola< T >::_fantasma, DCola< T >::_numElems, and DCola< T >::Nodo::_sig.
template<class T> DCola< T >::~DCola () [inline]
Destructor; elimina la lista doblemente enlazada.
Definition at line 50 of file DCola.h.
References DCola< T >::libera().
template<class T> DCola< T >::DCola (const DCola< T > & other) [inline]
Constructor copia
Definition at line 173 of file DCola.h.
References DCola< T >::copia().
Member Function Documentation
template<class T> static void DCola< T >::borraElem (Nodo * n) [inline, static, private]
Elimina el nodo n. Si el nodo tiene nodos antes o después, actualiza sus punteros anterior y siguiente. Caso general: hay nodos anterior y siguiente. Casos especiales: algunos de los nodos (anterior o siguiente a n) no existen.
Definition at line 278 of file DCola.h.
References DCola< T >::Nodo::_ant, and DCola< T >::Nodo::_sig.
Referenced by DCola< T >::quitaPrim(), and DCola< T >::quitaUlt().
template<class T> void DCola< T >::copia (const DCola< T > & other) [inline, protected]
Definition at line 218 of file DCola.h.
References DCola< T >::Nodo::_ant, DCola< T >::Nodo::_elem, DCola< T >::_fantasma, DCola< T >::_numElems, DCola< T >::Nodo::_sig, and DCola< T >::ponDetras().
Referenced by DCola< T >::DCola(), and DCola< T >::operator=().
template<class T> bool DCola< T >::esVacia () const [inline]
Operación observadora para saber si una doble cola tiene o no elementos.
esVacia(DColaVacia) = true esVacia(ponDetras(x, xs)) = false
Returns:
true si la doble cola no tiene elementos.
Definition at line 150 of file DCola.h.
References DCola< T >::_fantasma, and DCola< T >::Nodo::_sig.
Referenced by DCola< T >::primero(), DCola< T >::quitaPrim(), DCola< T >::quitaUlt(), and DCola< T >::ultimo().
template<class T> static Nodo* DCola< T >::insertaElem (const T & e, Nodo * nodo1, Nodo * nodo2) [inline, static, private]
Inserta un elemento entre el nodo1 y el nodo2. Devuelve el puntero al nodo creado. Caso general: los dos nodos existen. nodo1->_sig == nodo2 nodo2->_ant == nodo1 Casos especiales: alguno de los nodos no existe nodo1 == NULL y/o nodo2 == NULL
Definition at line 262 of file DCola.h.
References DCola< T >::Nodo::_ant, and DCola< T >::Nodo::_sig.
Referenced by DCola< T >::ponDelante(), and DCola< T >::ponDetras().
template<class T> void DCola< T >::libera () [inline, protected]
Definition at line 208 of file DCola.h.
References DCola< T >::Nodo::_ant, DCola< T >::_fantasma, and DCola< T >::Nodo::_sig.
Referenced by DCola< T >::operator=(), and DCola< T >::~DCola().
template<class T> static void DCola< T >::libera (Nodo * prim) [inline, static, private]
Elimina todos los nodos de la lista enlazada cuyo primer nodo se pasa como parámetro. Se admite que el nodo sea NULL (no habrá nada que liberar). En caso de pasarse un nodo válido, su puntero al nodo anterior debe ser NULL (si no, no sería el primero de la lista!).
Definition at line 299 of file DCola.h.
References DCola< T >::Nodo::_ant, and DCola< T >::Nodo::_sig.
template<class T> int DCola< T >::numElems () const [inline]
Devuelve el número de elementos que hay en la doble cola. numElems(DColaVacia) = 0 numElems(PonDetras(elem, p)) = 1 + numElems(p)
Returns:
Número de elementos.
Definition at line 163 of file DCola.h.
References DCola< T >::_numElems.
template<class T> bool DCola< T >::operator!= (const DCola< T > & rhs) const [inline]
Definition at line 202 of file DCola.h.
template<class T> DCola<T>& DCola< T >::operator= (const DCola< T > & other) [inline]
Operador de asignación
Definition at line 178 of file DCola.h.
References DCola< T >::copia(), and DCola< T >::libera().
template<class T> bool DCola< T >::operator== (const DCola< T > & rhs) const [inline]
Operador de comparación.
Definition at line 187 of file DCola.h.
References DCola< T >::Nodo::_elem, DCola< T >::_fantasma, DCola< T >::_numElems, and DCola< T >::Nodo::_sig.
template<class T> void DCola< T >::ponDelante (const T & e) [inline]
Añade un elemento a la parte delantera de una doble cola. Operación modificadora.
ponDelante(elem, DColaVacia) = ponDetras(elem, DColaVacia) ponDelante(elem, ponDetras(x, xs)) = ponDetras(x, ponDelante(elem, xs))
Parameters:
e Elemento que se añade
Definition at line 106 of file DCola.h.
References DCola< T >::_fantasma, DCola< T >::_numElems, DCola< T >::Nodo::_sig, and DCola< T >::insertaElem().
template<class T> void DCola< T >::ponDetras (const T & e) [inline]
Añade un elemento por la parte de atrás de la cola. Es una operación generadora.
Definition at line 58 of file DCola.h.
References DCola< T >::Nodo::_ant, DCola< T >::_fantasma, DCola< T >::_numElems, and DCola< T >::insertaElem().
Referenced by DCola< T >::copia().
template<class T> const T& DCola< T >::primero () const [inline]
Devuelve el primer elemento de la cola; es una operación observadora parcial, pues es un error preguntar por el primer elemento de una doble cola vacía.
primero(PonDetras(elem, DColaVacia)) = elem primero(PonDetras(elem, xs)) = primero(xs) si !esVacia(xs) error: primero(DColaVacia)
Definition at line 72 of file DCola.h.
References DCola< T >::Nodo::_elem, DCola< T >::_fantasma, DCola< T >::Nodo::_sig, and DCola< T >::esVacia().
template<class T> void DCola< T >::quitaPrim () [inline]
Elimina el primer elemento de la doble cola. Operación modificadora parcial, que falla si está vacía.
quitaPrim(PonDetras(elem, DColaVacia)) = DColaVacia quitaPrim(PonDetras(elem, xs)) = PonDetras(elem, quitaPrim(xs)) si !esVacia(xs) error: quitaPrim(DColaVacia)
Definition at line 88 of file DCola.h.
References DCola< T >::_fantasma, DCola< T >::_numElems, DCola< T >::Nodo::_sig, DCola< T >::borraElem(), and DCola< T >::esVacia().
template<class T> void DCola< T >::quitaUlt () [inline]
Elimina el último elemento de la doble cola. Es un error quitar el último de una doble cola vacía.
quitaUlt(PonDetras(x, xs)) = xs error: quitaUlt(DColaVacia)
Definition at line 133 of file DCola.h.
References DCola< T >::Nodo::_ant, DCola< T >::_fantasma, DCola< T >::_numElems, DCola< T >::borraElem(), and DCola< T >::esVacia().
template<class T> const T& DCola< T >::ultimo () const [inline]
Devuelve el último elemento de la doble cola. Es un error preguntar por el último de una doble cola vacía.
ultimo(PonDetras(x, xs)) = x error: ultimo(DColaVacia)
Returns:
Último elemento de la cola.
Definition at line 120 of file DCola.h.
References DCola< T >::Nodo::_ant, DCola< T >::Nodo::_elem, DCola< T >::_fantasma, and DCola< T >::esVacia().
Member Data Documentation
template<class T> Nodo* DCola< T >::_fantasma [private]
Definition at line 313 of file DCola.h.
Referenced by DCola< T >::copia(), DCola< T >::DCola(), DCola< T >::esVacia(), DCola< T >::libera(), DCola< T >::operator==(), DCola< T >::ponDelante(), DCola< T >::ponDetras(), DCola< T >::primero(), DCola< T >::quitaPrim(), DCola< T >::quitaUlt(), and DCola< T >::ultimo().
template<class T> unsigned int DCola< T >::_numElems [private]
Definition at line 316 of file DCola.h.
Referenced by DCola< T >::copia(), DCola< T >::DCola(), DCola< T >::numElems(), DCola< T >::operator==(), DCola< T >::ponDelante(), DCola< T >::ponDetras(), DCola< T >::quitaPrim(), and DCola< T >::quitaUlt().
The documentation for this class was generated from the following file:
include/DCola.h