Tiposabstractosdedatos: Arbus< Clave, Valor > Class Template Reference
Arbus< Clave, Valor > Class Template Reference
#include <Arbus.h>
Classes
class Iterador
class Nodo
Public Member Functions
Arbus ()
~Arbus ()
void inserta (const Clave &clave, const Valor &valor)
void borra (const Clave &clave)
const Valor & consulta (const Clave &clave)
bool esta (const Clave &clave)
bool esVacio () const
Iterador principio ()
Iterador final () const
Arbus (const Arbus< Clave, Valor > &other)
Arbus< Clave, Valor > & operator= (const Arbus< Clave, Valor > &other)
Protected Member Functions
Arbus (Nodo *raiz)
void libera ()
void copia (const Arbus &other)
Static Private Member Functions
static void libera (Nodo *ra)
static Nodo * copiaAux (Nodo *ra)
static Nodo * insertaAux (const Clave &clave, const Valor &valor, Nodo *p)
static Nodo * buscaAux (Nodo *p, const Clave &clave)
static Nodo * borraAux (Nodo *p, const Clave &clave)
static Nodo * borraRaiz (Nodo *p)
static Nodo * mueveMinYBorra (Nodo *p)
Private Attributes
Nodo * _ra
Detailed Description
template<class Clave, class Valor>
class Arbus< Clave, Valor >
Implementación dinámica del TAD Arbus utilizando nodos con un puntero al hijo izquierdo y otro al hijo derecho.
Las operaciones son:
ArbusVacio: operación generadora que construye un árbol de búsqueda vacío.
Inserta(clave, valor): generadora que añade una nueva pareja (clave, valor) al árbol. Si la clave ya estaba se sustituye el valor.
borra(clave): operación modificadora. Elimina la clave del árbol de búsqueda. Si la clave no está, la operación no tiene efecto.
consulta(clave): operación observadora que devuelve el valor asociado a una clave. Es un error preguntar por una clave que no existe.
esta(clave): operación observadora. Sirve para averiguar si se ha introducido una clave en el árbol.
esVacio(): operacion observadora que indica si el árbol de búsqueda tiene alguna clave introducida.
Author:
Marco Antonio Gómez Martín
Definition at line 53 of file Arbus.h.
Constructor & Destructor Documentation
template<class Clave, class Valor> Arbus< Clave, Valor >::Arbus () [inline]
Constructor; operacion ArbolVacio
Definition at line 76 of file Arbus.h.
template<class Clave, class Valor> Arbus< Clave, Valor >::~Arbus () [inline]
Destructor; elimina la estructura jerárquica de nodos.
Definition at line 80 of file Arbus.h.
References Arbus< Clave, Valor >::_ra, and Arbus< Clave, Valor >::libera().
template<class Clave, class Valor> Arbus< Clave, Valor >::Arbus (const Arbus< Clave, Valor > & other) [inline]
Constructor copia
Definition at line 265 of file Arbus.h.
References Arbus< Clave, Valor >::copia().
template<class Clave, class Valor> Arbus< Clave, Valor >::Arbus (Nodo * raiz) [inline, protected]
Constructor protegido que crea un árbol a partir de una estructura jerárquica de nodos previamente creada. Se utiliza en hijoIz e hijoDr.
Definition at line 286 of file Arbus.h.
Member Function Documentation
template<class Clave, class Valor> void Arbus< Clave, Valor >::borra (const Clave & clave) [inline]
Operación modificadora que elimina una clave del árbol. Si la clave no existía la operación no tiene efecto.
borra(elem, ArbusVacio) = ArbusVacio borra(e, inserta(c, v, arbol)) = inserta(c, v, borra(e, arbol)) si c != e borra(e, inserta(c, v, arbol)) = borra(e, arbol) si c == e
Parameters:
clave Clave a eliminar.
Definition at line 108 of file Arbus.h.
References Arbus< Clave, Valor >::_ra, and Arbus< Clave, Valor >::borraAux().
template<class Clave, class Valor> static Nodo* Arbus< Clave, Valor >::borraAux (Nodo * p, const Clave & clave) [inline, static, private]
Elimina (si existe) la clave/valor de la estructura jerárquica de nodos apuntada por p. Si la clave aparecía en la propia raíz, ésta cambiará, por lo que se devuelve la nueva raíz. Si no cambia se devuelve p.
Parameters:
p Raíz de la estructura jerárquica donde borrar la clave.
clave Clave a borrar.
Returns:
Nueva raíz de la estructura, tras el borrado. Si la raíz no cambia, se devuelve el propio p.
Definition at line 390 of file Arbus.h.
References Arbus< Clave, Valor >::Nodo::_clave, Arbus< Clave, Valor >::Nodo::_dr, Arbus< Clave, Valor >::Nodo::_iz, and Arbus< Clave, Valor >::borraRaiz().
Referenced by Arbus< Clave, Valor >::borra().
template<class Clave, class Valor> static Nodo* Arbus< Clave, Valor >::borraRaiz (Nodo * p) [inline, static, private]
Borra la raíz de la estructura jerárquica de nodos y devuelve el puntero a la nueva raíz que garantiza que la estructura sigue siendo válida para un árbol de búsqueda (claves ordenadas).
Definition at line 412 of file Arbus.h.
References Arbus< Clave, Valor >::Nodo::_dr, Arbus< Clave, Valor >::Nodo::_iz, and Arbus< Clave, Valor >::mueveMinYBorra().
Referenced by Arbus< Clave, Valor >::borraAux().
template<class Clave, class Valor> static Nodo* Arbus< Clave, Valor >::buscaAux (Nodo * p, const Clave & clave) [inline, static, private]
Busca una clave en la estructura jerárquica de nodos cuya raíz se pasa como parámetro, y devuelve el nodo en la que se encuentra (o NULL si no está).
Parameters:
p Puntero a la raíz de la estructura de nodos
clave Clave a buscar
Definition at line 366 of file Arbus.h.
References Arbus< Clave, Valor >::Nodo::_clave, Arbus< Clave, Valor >::Nodo::_dr, and Arbus< Clave, Valor >::Nodo::_iz.
Referenced by Arbus< Clave, Valor >::consulta(), and Arbus< Clave, Valor >::esta().
template<class Clave, class Valor> const Valor& Arbus< Clave, Valor >::consulta (const Clave & clave) [inline]
Operación observadora que devuelve el valor asociado a una clave dada.
consulta(e, inserta(c, v, arbol)) = v si e == c consulta(e, inserta(c, v, arbol)) = consulta(e, arbol) si e != c error consulta(ArbusVacio)
Parameters:
clave Clave por la que se pregunta.
Definition at line 122 of file Arbus.h.
References Arbus< Clave, Valor >::_ra, Arbus< Clave, Valor >::Nodo::_valor, and Arbus< Clave, Valor >::buscaAux().
template<class Clave, class Valor> void Arbus< Clave, Valor >::copia (const Arbus< Clave, Valor > & other) [inline, protected]
Definition at line 293 of file Arbus.h.
References Arbus< Clave, Valor >::_ra, and Arbus< Clave, Valor >::copiaAux().
Referenced by Arbus< Clave, Valor >::Arbus(), and Arbus< Clave, Valor >::operator=().
template<class Clave, class Valor> static Nodo* Arbus< Clave, Valor >::copiaAux (Nodo * ra) [inline, static, private]
Copia la estructura jerárquica de nodos pasada como parámetro (puntero a su raiz) y devuelve un puntero a una nueva estructura jerárquica, copia de anterior (y que, por tanto, habrá que liberar).
Definition at line 319 of file Arbus.h.
References Arbus< Clave, Valor >::Nodo::_clave, Arbus< Clave, Valor >::Nodo::_dr, Arbus< Clave, Valor >::Nodo::_iz, and Arbus< Clave, Valor >::Nodo::_valor.
Referenced by Arbus< Clave, Valor >::copia().
template<class Clave, class Valor> bool Arbus< Clave, Valor >::esta (const Clave & clave) [inline]
Operación observadora que permite averiguar si una clave determinada está o no en el árbol de búsqueda.
esta(e, ArbusVacio) = false esta(e, inserta(c, v, arbol)) = true si e == c esta(e, inserta(c, v, arbol)) = esta(e, arbol) si e != c
Parameters:
clave Clave por la que se pregunta.
Definition at line 140 of file Arbus.h.
References Arbus< Clave, Valor >::_ra, and Arbus< Clave, Valor >::buscaAux().
template<class Clave, class Valor> bool Arbus< Clave, Valor >::esVacio () const [inline]
Operación observadora que devuelve si el árbol es vacío (no contiene elementos) o no.
esVacio(ArbusVacio) = true esVacio(inserta(c, v, arbol)) = false
Definition at line 151 of file Arbus.h.
References Arbus< Clave, Valor >::_ra.
template<class Clave, class Valor> Iterador Arbus< Clave, Valor >::final () const [inline]
Returns:
Devuelve un iterador al final del recorrido (fuera de éste).
Definition at line 254 of file Arbus.h.
template<class Clave, class Valor> void Arbus< Clave, Valor >::inserta (const Clave & clave, const Valor & valor) [inline]
Operación generadora que añade una nueva clave/valor a un árbol de búsqueda.
Parameters:
clave Clave nueva.
valor Valor asociado a esa clave. Si la clave ya se había insertado previamente, sustituimos el valor viejo por el nuevo.
Definition at line 93 of file Arbus.h.
References Arbus< Clave, Valor >::_ra, and Arbus< Clave, Valor >::insertaAux().
template<class Clave, class Valor> static Nodo* Arbus< Clave, Valor >::insertaAux (const Clave & clave, const Valor & valor, Nodo * p) [inline, static, private]
Inserta una pareja (clave, valor) en la estructura jerárquica que comienza en el puntero pasado como parámetro. Ese puntero se admite que sea NULL, por lo que se creará un nuevo nodo que pasará a ser la nueva raíz de esa estructura jerárquica. El método devuelve un puntero a la raíz de la estructura modificada. En condiciones normales coincidirá con el parámetro recibido; sólo cambiará si la estructura era vacía.
Parameters:
clave Clave a insertar. Si ya aparecía en la estructura de nodos, se sobreescribe el valor.
valor Valor a insertar.
p Puntero al nodo raíz donde insertar la pareja.
Returns:
Nueva raíz (o p si no cambia).
Definition at line 343 of file Arbus.h.
References Arbus< Clave, Valor >::Nodo::_clave, Arbus< Clave, Valor >::Nodo::_dr, Arbus< Clave, Valor >::Nodo::_iz, and Arbus< Clave, Valor >::Nodo::_valor.
Referenced by Arbus< Clave, Valor >::inserta().
template<class Clave, class Valor> void Arbus< Clave, Valor >::libera () [inline, protected]
Definition at line 289 of file Arbus.h.
References Arbus< Clave, Valor >::_ra.
Referenced by Arbus< Clave, Valor >::libera(), Arbus< Clave, Valor >::operator=(), and Arbus< Clave, Valor >::~Arbus().
template<class Clave, class Valor> static void Arbus< Clave, Valor >::libera (Nodo * ra) [inline, static, private]
Elimina todos los nodos de una estructura arbórea que comienza con el puntero ra. Se admite que el nodo sea NULL (no habrá nada que liberar).
Definition at line 305 of file Arbus.h.
References Arbus< Clave, Valor >::Nodo::_dr, Arbus< Clave, Valor >::Nodo::_iz, and Arbus< Clave, Valor >::libera().
template<class Clave, class Valor> static Nodo* Arbus< Clave, Valor >::mueveMinYBorra (Nodo * p) [inline, static, private]
Método auxiliar para el borrado; recibe un puntero a la raíz a borrar. Busca el elemento más pequeño del hijo derecho que se convertirá en la raíz (que devolverá), borra la antigua raíz (p) y "cose" todos los punteros, de forma que ahora:
El mínimo pasa a ser la raíz, cuyo hijo izquierdo y derecho eran los hijos izquierdo y derecho de la raíz antigua.
El hijo izquierdo del padre del elemento más pequeño pasa a ser el antiguo hijo derecho de ese mínimo.
Definition at line 448 of file Arbus.h.
References Arbus< Clave, Valor >::Nodo::_dr, and Arbus< Clave, Valor >::Nodo::_iz.
Referenced by Arbus< Clave, Valor >::borraRaiz().
template<class Clave, class Valor> Arbus<Clave, Valor>& Arbus< Clave, Valor >::operator= (const Arbus< Clave, Valor > & other) [inline]
Operador de asignación
Definition at line 270 of file Arbus.h.
References Arbus< Clave, Valor >::copia(), and Arbus< Clave, Valor >::libera().
template<class Clave, class Valor> Iterador Arbus< Clave, Valor >::principio () [inline]
Devuelve el iterador al principio de la lista.
Returns:
iterador al principio de la lista; coincidirá con final() si la lista está vacía.
Definition at line 246 of file Arbus.h.
References Arbus< Clave, Valor >::_ra.
Member Data Documentation
template<class Clave, class Valor> Nodo* Arbus< Clave, Valor >::_ra [private]
Puntero a la raíz de la estructura jerárquica de nodos.
Definition at line 484 of file Arbus.h.
Referenced by Arbus< Clave, Valor >::borra(), Arbus< Clave, Valor >::consulta(), Arbus< Clave, Valor >::copia(), Arbus< Clave, Valor >::esta(), Arbus< Clave, Valor >::esVacio(), Arbus< Clave, Valor >::inserta(), Arbus< Clave, Valor >::libera(), Arbus< Clave, Valor >::principio(), and Arbus< Clave, Valor >::~Arbus().
The documentation for this class was generated from the following file:
include/Arbus.h