Tiposabstractosdedatos: Arbus< Clave, Valor >::Iterador Class Reference
Arbus< Clave, Valor >::Iterador Class Reference
#include <Arbus.h>
Public Member Functions
void avanza ()
const Clave & clave () const
const Valor & valor () const
bool operator== (const Iterador &other) const
bool operator!= (const Iterador &other) const
Protected Member Functions
Iterador ()
Iterador (Nodo *act)
Nodo * primeroInOrden (Nodo *p)
Protected Attributes
Nodo * _act
Pila< Nodo * > _ascendientes
Friends
class Arbus
Detailed Description
template<class Clave, class Valor>
class Arbus< Clave, Valor >::Iterador
Clase interna que implementa un iterador sobre la lista que permite recorrer la lista e incluso alterar el valor de sus elementos.
Definition at line 164 of file Arbus.h.
Constructor & Destructor Documentation
template<class Clave, class Valor> Arbus< Clave, Valor >::Iterador::Iterador () [inline, protected]
Definition at line 209 of file Arbus.h.
template<class Clave, class Valor> Arbus< Clave, Valor >::Iterador::Iterador (Nodo * act) [inline, protected]
Definition at line 210 of file Arbus.h.
References Arbus< Clave, Valor >::Iterador::_act, and Arbus< Clave, Valor >::Iterador::primeroInOrden().
Member Function Documentation
template<class Clave, class Valor> void Arbus< Clave, Valor >::Iterador::avanza () [inline]
Definition at line 166 of file Arbus.h.
References Arbus< Clave, Valor >::Iterador::_act, Arbus< Clave, Valor >::Iterador::_ascendientes, Arbus< Clave, Valor >::Nodo::_dr, Pila< T >::cima(), Pila< T >::desapila(), Pila< T >::esVacia(), and Arbus< Clave, Valor >::Iterador::primeroInOrden().
template<class Clave, class Valor> const Clave& Arbus< Clave, Valor >::Iterador::clave () const [inline]
Definition at line 187 of file Arbus.h.
References Arbus< Clave, Valor >::Iterador::_act, and Arbus< Clave, Valor >::Nodo::_clave.
template<class Clave, class Valor> bool Arbus< Clave, Valor >::Iterador::operator!= (const Iterador & other) const [inline]
Definition at line 201 of file Arbus.h.
References Arbus< Clave, Valor >::Iterador::operator==().
template<class Clave, class Valor> bool Arbus< Clave, Valor >::Iterador::operator== (const Iterador & other) const [inline]
Definition at line 197 of file Arbus.h.
References Arbus< Clave, Valor >::Iterador::_act.
Referenced by Arbus< Clave, Valor >::Iterador::operator!=().
template<class Clave, class Valor> Nodo* Arbus< Clave, Valor >::Iterador::primeroInOrden (Nodo * p) [inline, protected]
Busca el primer elemento en inorden de la estructura jerárquica de nodos pasada como parámetro; va apilando sus ascendientes para poder "ir hacia atrás" cuando sea necesario.
Parameters:
p Puntero a la raíz de la subestructura.
Definition at line 221 of file Arbus.h.
References Arbus< Clave, Valor >::Iterador::_ascendientes, Arbus< Clave, Valor >::Nodo::_iz, and Pila< T >::apila().
Referenced by Arbus< Clave, Valor >::Iterador::avanza(), and Arbus< Clave, Valor >::Iterador::Iterador().
template<class Clave, class Valor> const Valor& Arbus< Clave, Valor >::Iterador::valor () const [inline]
Definition at line 192 of file Arbus.h.
References Arbus< Clave, Valor >::Iterador::_act, and Arbus< Clave, Valor >::Nodo::_valor.
Friends And Related Function Documentation
template<class Clave, class Valor> friend class Arbus [friend]
Definition at line 207 of file Arbus.h.
Member Data Documentation
template<class Clave, class Valor> Nodo* Arbus< Clave, Valor >::Iterador::_act [protected]
Definition at line 234 of file Arbus.h.
Referenced by Arbus< Clave, Valor >::Iterador::avanza(), Arbus< Clave, Valor >::Iterador::clave(), Arbus< Clave, Valor >::Iterador::Iterador(), Arbus< Clave, Valor >::Iterador::operator==(), and Arbus< Clave, Valor >::Iterador::valor().
template<class Clave, class Valor> Pila<Nodo*> Arbus< Clave, Valor >::Iterador::_ascendientes [protected]
Definition at line 238 of file Arbus.h.
Referenced by Arbus< Clave, Valor >::Iterador::avanza(), and Arbus< Clave, Valor >::Iterador::primeroInOrden().
The documentation for this class was generated from the following file:
include/Arbus.h