CREATE TABLE EMPLEADOS
  (
    NOMBRE             VARCHAR(50) NOT NULL,
    DNI                VARCHAR(9) NOT NULL,
    SUELDO             DECIMAL(6,2) NOT NULL,
    "FECHA NACIMIENTO" DATE NOT NULL,
    PRIMARY KEY (DNI)
  );
CREATE TABLE "CÓDIGOS POSTALES"
  (
    "CÓDIGO POSTAL" VARCHAR(5) NOT NULL,
    POBLACIÓN       VARCHAR(50) NOT NULL,
    PROVINCIA       VARCHAR(50) NOT NULL,
    PRIMARY KEY ("CÓDIGO POSTAL")
  );
CREATE TABLE DOMICILIOS
  (
    DNI             VARCHAR(9) NOT NULL,
    CALLE           VARCHAR(50),
    "CÓDIGO POSTAL" VARCHAR(5),
    PRIMARY KEY (DNI, "CÓDIGO POSTAL"),
    FOREIGN KEY (DNI) REFERENCES EMPLEADOS (DNI),
    FOREIGN KEY ("CÓDIGO POSTAL") REFERENCES "CÓDIGOS POSTALES" ("CÓDIGO POSTAL")
  );
CREATE TABLE TELÉFONOS
  (
    DNI      VARCHAR(9) NOT NULL,
    TELÉFONO VARCHAR(9),
    PRIMARY KEY (DNI, TELÉFONO),
    FOREIGN KEY (DNI) REFERENCES EMPLEADOS (DNI)
  );