CREATE
  TABLE EMPLEADOS
  (
    DNI                VARCHAR(9) NOT NULL,
    NOMBRE             VARCHAR(255),
    SUELDO             NUMBER,
    "FECHA NACIMIENTO" DATE,
    PRIMARY KEY(DNI)
  );

CREATE
  TABLE "CÓDIGOS POSTALES"
  (
    "CÓDIGO POSTAL" VARCHAR(5) NOT NULL,
    "POBLACIÓN"     VARCHAR(50),
    PROVINCIA       VARCHAR(50),
    PRIMARY KEY("CÓDIGO POSTAL")
  );
  
CREATE
  TABLE "TELÉFONOS"
  (
    DNI         VARCHAR(9) NOT NULL,
    "TELÉFONOS" VARCHAR(9),
    PRIMARY KEY(DNI, "TELÉFONOS"),
    FOREIGN KEY(DNI) REFERENCES EMPLEADOS(DNI)
  );

CREATE
  TABLE DOMICILIOS
  (
    DNI             VARCHAR(9) NOT NULL,
    CALLE           VARCHAR(50),
    "CÓDIGO POSTAL" VARCHAR(5),
    PRIMARY KEY(DNI),
    FOREIGN KEY(DNI) REFERENCES EMPLEADOS(DNI),
    FOREIGN KEY("CÓDIGO POSTAL") REFERENCES "CÓDIGOS POSTALES"("CÓDIGO POSTAL")
  );
