SELECT
	NOMBRE, 
	EMPLEADOS.DNI,
	CALLE,
	POBLACIÓN,
	PROVINCIA,
	DOMICILIOS."CÓDIGO POSTAL"
	TELÉFONO
FROM
	EMPLEADOS 
LEFT JOIN
	DOMICILIOS 
ON
	EMPLEADOS.DNI = DOMICILIOS.DNI
LEFT JOIN
	"CÓDIGOS POSTALES" 
ON
	DOMICILIOS."CÓDIGO POSTAL" = "CÓDIGOS POSTALES"."CÓDIGO POSTAL"
LEFT JOIN
	TELÉFONOS
ON
	EMPLEADOS.DNI = TELÉFONOS.DNI
ORDER BY
	NOMBRE ASC;