SELECT
	AVG(SUELDO) AS "SUELDO MEDIO",
	COUNT(EMPLEADOS.DNI) AS "NÚMERO DE EMPLEADOS",
	POBLACIÓN AS "POBLACIÓN"
FROM
	"CÓDIGOS POSTALES"
JOIN
	DOMICILIOS
ON
	"CÓDIGOS POSTALES"."CÓDIGO POSTAL" = DOMICILIOS."CÓDIGO POSTAL"
RIGHT OUTER JOIN
	EMPLEADOS
ON
	DOMICILIOS.DNI = EMPLEADOS.DNI
GROUP BY
	POBLACIÓN
ORDER BY
	POBLACIÓN ASC;