SELECT
	NOMBRE, 
	EMPLEADOS.DNI,
	CALLE,
	POBLACIÓN,
	PROVINCIA,
	DOMICILIOS."CÓDIGO POSTAL"
FROM
	EMPLEADOS 
LEFT JOIN
	DOMICILIOS 
ON
	EMPLEADOS.DNI = DOMICILIOS.DNI
LEFT JOIN
	"CÓDIGOS POSTALES"
ON
	DOMICILIOS."CÓDIGO POSTAL" = "CÓDIGOS POSTALES"."CÓDIGO POSTAL"
ORDER BY
	NOMBRE ASC;