SELECT
	C1.POBLACIÓN AS "POBLACIÓN",
	C2."CÓDIGO POSTAL" AS "Barcelona",
	C3."CÓDIGO POSTAL" AS "Córdoba",
	C4."CÓDIGO POSTAL" AS "Madrid",
	C5."CÓDIGO POSTAL" AS "Zaragoza"
FROM
	"CÓDIGOS POSTALES" C1
LEFT JOIN
	"CÓDIGOS POSTALES" C2
ON
	C2.PROVINCIA = 'Barcelona' AND
	C2.POBLACIÓN = C1."POBLACIÓN"
LEFT JOIN
	"CÓDIGOS POSTALES" C3
ON
	C3.PROVINCIA = 'Córdoba' AND
	C3.POBLACIÓN = C1."POBLACIÓN"
LEFT JOIN
	"CÓDIGOS POSTALES" C4
ON
	C4.PROVINCIA = 'Madrid' AND
	C4.POBLACIÓN = C1."POBLACIÓN"
LEFT JOIN
	"CÓDIGOS POSTALES" C5
ON
	C5.PROVINCIA = 'Zaragoza' AND
	C5.POBLACIÓN = C1."POBLACIÓN"
ORDER BY
	C1."POBLACIÓN" ASC;